# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc7a17bf0e9e3b2fa558808c2149d3f0fd160ed90fa409558bf3667beb34986458a5b28fe3065138e0a905bbd10c3726d021350c548e7c496d1c1cb42f6c4a06

test:
  secret_key_base: 6706de93c263b7577fdae8306b13c1e6dd94efe46af7401fe8c0c585209ef1866a4983f0a31acde33f6118ce507bceaffce4a5bfd945842c6e3a527dd0c923cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
